# Generated by Django 4.2.23 on 2025-09-09 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotAvailability',
            fields=[
                ('calendar_date', models.DateField(primary_key=True, serialize=False)),
                ('total_cust_demand_for_tables_17_18', models.IntegerField(default=0)),
                ('number_of_tables_available_17_18', models.IntegerField(default=10)),
                ('total_cust_demand_for_tables_18_19', models.IntegerField(default=0)),
                ('number_of_tables_available_18_19', models.IntegerField(default=10)),
                ('total_cust_demand_for_tables_19_20', models.IntegerField(default=0)),
                ('number_of_tables_available_19_20', models.IntegerField(default=10)),
                ('total_cust_demand_for_tables_20_21', models.IntegerField(default=0)),
                ('number_of_tables_available_20_21', models.IntegerField(default=10)),
                ('total_cust_demand_for_tables_21_22', models.IntegerField(default=0)),
                ('number_of_tables_available_21_22', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_slot', models.CharField(max_length=20)),
                ('number_of_tables_required_by_patron', models.PositiveIntegerField()),
                ('reservation_status', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('timeslot_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_book.timeslotavailability')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
