# Generated by Django 4.2.23 on 2026-01-06 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barred', models.BooleanField(default=False, help_text='Check if this customer is not welcome (no new bookings allowed)')),
                ('notes', models.TextField(blank=True, help_text='Staff notes: e.g., VIP, regular, allergy, restaurant critic, supplier, chef, etc.')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tables_per_slot', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Restaurant Configuration',
                'verbose_name_plural': 'Restaurant Configuration',
            },
        ),
        migrations.CreateModel(
            name='TimeSlotAvailability',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calendar_date', models.DateField(unique=True)),
                ('total_cust_demand_for_tables_17_18', models.PositiveIntegerField(default=0)),
                ('total_cust_demand_for_tables_18_19', models.PositiveIntegerField(default=0)),
                ('total_cust_demand_for_tables_19_20', models.PositiveIntegerField(default=0)),
                ('total_cust_demand_for_tables_20_21', models.PositiveIntegerField(default=0)),
                ('total_cust_demand_for_tables_21_22', models.PositiveIntegerField(default=0)),
                ('number_of_tables_available_17_18', models.PositiveIntegerField(default=0)),
                ('number_of_tables_available_18_19', models.PositiveIntegerField(default=0)),
                ('number_of_tables_available_19_20', models.PositiveIntegerField(default=0)),
                ('number_of_tables_available_20_21', models.PositiveIntegerField(default=0)),
                ('number_of_tables_available_21_22', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField(blank=True, help_text='Denormalized date from the related TimeSlotAvailability.', null=True)),
                ('time_slot', models.CharField(help_text="Which time slot was reserved (e.g. '17_18').", max_length=20)),
                ('duration_hours', models.PositiveSmallIntegerField(choices=[(1, '1 hour'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours')], default=1, help_text='How many consecutive hours this booking requires (max 4)')),
                ('number_of_tables_required_by_patron', models.PositiveIntegerField()),
                ('reservation_status', models.BooleanField(default=True)),
                ('is_phone_reservation', models.BooleanField(default=False, help_text='True if this reservation was taken over the phone by staff.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created this reservation (for phone bookings)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation_book.customer')),
                ('timeslot_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation_book.timeslotavailability')),
            ],
        ),
    ]
