# Generated by Django 4.2.23 on 2025-09-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationBook',
        ),
    ]
