# Generated by Django 4.2.23 on 2025-09-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tables_per_slot', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Restaurant Configuration',
                'verbose_name_plural': 'Restaurant Configuration',
            },
        ),
    ]
