# Generated by Django 4.2.23 on 2026-01-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # <-- change to your actual latest migration
        ("reservation_book", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="timeslotavailability",
                    name="id",
                ),
                migrations.AlterField(
                    model_name="timeslotavailability",
                    name="calendar_date",
                    field=models.DateField(primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
