# Generated by Django 4.2.23 on 2025-09-08 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation_book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BridgeEntity',
        ),
        migrations.DeleteModel(
            name='ContactMobile',
        ),
        migrations.DeleteModel(
            name='ContactPhone',
        ),
        migrations.DeleteModel(
            name='Creditos1',
        ),
        migrations.DeleteModel(
            name='ReservedTables1718',
        ),
        migrations.DeleteModel(
            name='ReservedTables1819',
        ),
        migrations.DeleteModel(
            name='ReservedTables1920',
        ),
        migrations.DeleteModel(
            name='ReservedTables2021',
        ),
        migrations.DeleteModel(
            name='ReservedTables2122',
        ),
        migrations.RemoveField(
            model_name='onlineregisteredcustomer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='onlineregisteredcustomer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='onlineregisteredcustomer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationbook',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservation_book.onlineregisteredcustomer'),
        ),
        migrations.AlterField(
            model_name='onlineregisteredcustomer',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineregisteredcustomer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
