# Generated by Django 4.2.23 on 2025-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='reservation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
