# Generated by Django 4.2.23 on 2025-08-31 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationbook',
            name='first_name',
            field=models.CharField(default='first name', max_length=15),
        ),
        migrations.AddField(
            model_name='reservationbook',
            name='last_name',
            field=models.CharField(default='last name', max_length=15),
        ),
        migrations.AddField(
            model_name='reservationbook',
            name='reservation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reservationbook',
            name='reservation_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='reservation_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reservation_book.reservationbook'),
        ),
    ]
