# Generated by Django 4.2.23 on 2025-09-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0002_delete_reservationbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
