# Generated by Django 4.2.23 on 2025-08-31 18:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0002_reservationbook_first_name_reservationbook_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationbook',
            name='email',
            field=models.EmailField(default='me@domain.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reservationbook',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+49 123 456 78', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='reservationbook',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+49 123 456 78', max_length=128, region=None),
        ),
    ]
