# Generated by Django 4.2.23 on 2025-09-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0003_reservationbook_email_reservationbook_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotAvailability',
            fields=[
                ('calendar_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reservation_book.tablereservation')),
                ('total_cust_demand_for_tables_17_18', models.IntegerField()),
                ('number_of_tables_available_17_18', models.IntegerField()),
                ('total_cust_demand_for_tables_18_19', models.IntegerField()),
                ('number_of_tables_available_18_19', models.IntegerField()),
                ('total_cust_demand_for_tables_19_20', models.IntegerField()),
                ('number_of_tables_available_19_20', models.IntegerField()),
                ('total_cust_demand_for_tables_20_21', models.IntegerField()),
                ('number_of_tables_available_20_21', models.IntegerField()),
                ('total_cust_demand_for_tables_21_22', models.IntegerField()),
                ('number_of_tables_available_21_22', models.IntegerField()),
            ],
        ),
    ]
