# Generated by Django 4.2.23 on 2026-01-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0003_reservationseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='series',
            field=models.ForeignKey(blank=True, help_text='If set, this reservation is part of a multi-day series booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservation_book.reservationseries'),
        ),
    ]
