# Generated by Django 4.2.23 on 2025-09-02 20:09

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0004_timeslotavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeEntity',
            fields=[
                ('calendar_date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineRegisteredCustomer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='first name', max_length=15)),
                ('last_name', models.CharField(default='last name', max_length=15)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+49 123 456 78', max_length=128, region=None)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(default='+49 123 456 78', max_length=128, region=None)),
                ('email', models.EmailField(default='me@domain.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedTables1718',
            fields=[
                ('calendar_date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('timme_slot', models.CharField(default='17:00 to 18:00', max_length=15)),
                ('table_1', models.IntegerField(default=0)),
                ('table_2', models.IntegerField(default=0)),
                ('table_3', models.IntegerField(default=0)),
                ('table_4', models.IntegerField(default=0)),
                ('table_5', models.IntegerField(default=0)),
                ('table_6', models.IntegerField(default=0)),
                ('table_7', models.IntegerField(default=0)),
                ('table_8', models.IntegerField(default=0)),
                ('table_9', models.IntegerField(default=0)),
                ('table_10', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedTables1819',
            fields=[
                ('calendar_date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('timme_slot', models.CharField(default='18:00 to 19:00', max_length=15)),
                ('table_1', models.IntegerField(default=0)),
                ('table_2', models.IntegerField(default=0)),
                ('table_3', models.IntegerField(default=0)),
                ('table_4', models.IntegerField(default=0)),
                ('table_5', models.IntegerField(default=0)),
                ('table_6', models.IntegerField(default=0)),
                ('table_7', models.IntegerField(default=0)),
                ('table_8', models.IntegerField(default=0)),
                ('table_9', models.IntegerField(default=0)),
                ('table_10', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedTables1920',
            fields=[
                ('calendar_date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('timme_slot', models.CharField(default='19:00 to 20:00', max_length=15)),
                ('table_1', models.IntegerField(default=0)),
                ('table_2', models.IntegerField(default=0)),
                ('table_3', models.IntegerField(default=0)),
                ('table_4', models.IntegerField(default=0)),
                ('table_5', models.IntegerField(default=0)),
                ('table_6', models.IntegerField(default=0)),
                ('table_7', models.IntegerField(default=0)),
                ('table_8', models.IntegerField(default=0)),
                ('table_9', models.IntegerField(default=0)),
                ('table_10', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedTables2021',
            fields=[
                ('calendar_date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('timme_slot', models.CharField(default='20:00 to 21:00', max_length=15)),
                ('table_1', models.IntegerField(default=0)),
                ('table_2', models.IntegerField(default=0)),
                ('table_3', models.IntegerField(default=0)),
                ('table_4', models.IntegerField(default=0)),
                ('table_5', models.IntegerField(default=0)),
                ('table_6', models.IntegerField(default=0)),
                ('table_7', models.IntegerField(default=0)),
                ('table_8', models.IntegerField(default=0)),
                ('table_9', models.IntegerField(default=0)),
                ('table_10', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedTables2122',
            fields=[
                ('calendar_date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('timme_slot', models.CharField(default='21:00 to 22:00', max_length=15)),
                ('table_1', models.IntegerField(default=0)),
                ('table_2', models.IntegerField(default=0)),
                ('table_3', models.IntegerField(default=0)),
                ('table_4', models.IntegerField(default=0)),
                ('table_5', models.IntegerField(default=0)),
                ('table_6', models.IntegerField(default=0)),
                ('table_7', models.IntegerField(default=0)),
                ('table_8', models.IntegerField(default=0)),
                ('table_9', models.IntegerField(default=0)),
                ('table_10', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='booked_on_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='number_of_tables_required_by_patron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='reservation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='reservation_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='time_slot',
            field=models.CharField(default='time_slot', max_length=15),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='number_of_tables_available_17_18',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='number_of_tables_available_18_19',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='number_of_tables_available_19_20',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='number_of_tables_available_20_21',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='number_of_tables_available_21_22',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='total_cust_demand_for_tables_17_18',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='total_cust_demand_for_tables_18_19',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='total_cust_demand_for_tables_19_20',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='total_cust_demand_for_tables_20_21',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='total_cust_demand_for_tables_21_22',
            field=models.IntegerField(default=0),
        ),
    ]
