# Generated by Django 4.2.23 on 2026-01-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0004_tablereservation_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='number_of_tables_required_by_patron',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
