# Generated by Django 4.2.23 on 2026-01-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0005_alter_tablereservation_number_of_tables_required_by_patron'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No-show')], db_index=True, default='active', help_text='Reservation lifecycle status for operations and reporting.', max_length=20),
        ),
    ]
