# Generated by Django 4.2.23 on 2025-09-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0005_bridgeentity_onlineregisteredcustomer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotavailability',
            name='number_of_tables_available_17_18',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='number_of_tables_available_18_19',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='number_of_tables_available_19_20',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='number_of_tables_available_20_21',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='timeslotavailability',
            name='number_of_tables_available_21_22',
            field=models.IntegerField(default=10),
        ),
    ]
