# Generated by Django 4.2.23 on 2026-01-29 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation_book', '0006_tablereservation_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who created this reservation (for phone bookings).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 hour'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours')], default=1, help_text='How many consecutive hours this booking requires (max 4).'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='reservation_status',
            field=models.BooleanField(db_index=True, default=True, help_text='Legacy flag kept for backward compatibility; prefer `status`.'),
        ),
    ]
