# Generated by Django 4.2.23 on 2026-02-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0007_alter_tablereservation_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by_staff', models.BooleanField(default=False)),
                ('reservation_date', models.DateField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=20)),
                ('tables', models.IntegerField(default=0)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 time slot'), (2, '2 time slots'), (3, '3 time slots'), (4, '4 time slots'), (5, '5 time slots')], default=1, help_text='How many consecutive time slots this booking requires (max 5).'),
        ),
    ]
