# Generated by Django 4.2.23 on 2026-02-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0008_cancellationevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationevent',
            name='duration_slots',
            field=models.IntegerField(default=1),
        ),
    ]
