# Generated by Django 4.2.23 on 2026-02-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0009_cancellationevent_duration_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStats',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('cancelled_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
