# Generated by Django 4.2.23 on 2026-02-21 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0010_reservationstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancellationevent',
            old_name='cancelled_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='customer_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='duration_slots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='reservation_date',
            field=models.DateField(db_index=True, default=datetime.date(2026, 2, 21)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='reservation_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='tables',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='time_slot',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
