# Generated by Django 4.2.23 on 2026-02-21 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0011_rename_cancelled_at_cancellationevent_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoShowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation_id', models.IntegerField(blank=True, null=True)),
                ('reservation_date', models.DateField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, default='', max_length=20)),
                ('tables', models.PositiveIntegerField(default=0)),
                ('duration_slots', models.PositiveIntegerField(default=1)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('marked_by_staff', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cancellationevent',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cancellationevent',
            name='cancelled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='reservation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='tables',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='time_slot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
