# Generated by Django 4.2.23 on 2026-02-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0012_noshowevent_remove_cancellationevent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noshowevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='noshowevent',
            name='marked_by_staff',
        ),
        migrations.AddField(
            model_name='customer',
            name='cancellations_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_show_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noshowevent',
            name='customer_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='noshowevent',
            name='reservation_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='noshowevent',
            name='reservation_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='noshowevent',
            name='time_slot',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
