# Generated by Django 4.2.23 on 2026-02-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0013_alter_noshowevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancellationevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='cancellationevent',
            name='cancelled_at',
        ),
        migrations.AddField(
            model_name='cancellationevent',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='customer_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='reservation_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='reservation_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancellationevent',
            name='time_slot',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
