# Generated by Django 4.2.23 on 2026-02-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0014_alter_cancellationevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noshowevent',
            name='marked_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
