# Generated by Django 4.2.23 on 2026-02-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_book', '0015_noshowevent_marked_by_staff'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cancellationevent',
            constraint=models.UniqueConstraint(fields=('reservation_id',), name='uniq_cancellationevent_reservation_id'),
        ),
        migrations.AddConstraint(
            model_name='noshowevent',
            constraint=models.UniqueConstraint(fields=('reservation_id',), name='uniq_noshowevent_reservation_id'),
        ),
    ]
