# Generated by Django 4.2.23 on 2026-03-10 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation_book', '0016_cancellationevent_uniq_cancellationevent_reservation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='barred',
            field=models.BooleanField(default=False, help_text='Check if this customer is not welcome             (no new bookings allowed)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Staff notes: e.g., VIP, regular, allergy,             restaurant critic, supplier, chef, etc.'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who created this reservation             (for phone bookings).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 time slot'), (2, '2 time slots'), (3, '3 time slots'), (4, '4 time slots'), (5, '5 time slots')], default=1, help_text='How many consecutive time slots             this booking requires (max 5).'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='is_phone_reservation',
            field=models.BooleanField(default=False, help_text='True if this reservation was             taken over the phone by staff.'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='reservation_status',
            field=models.BooleanField(db_index=True, default=True, help_text='Legacy flag kept for backward compatibility;             prefer `status`.'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='series',
            field=models.ForeignKey(blank=True, help_text='If set, this reservation is part of a             multi-day series booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservation_book.reservationseries'),
        ),
    ]
