"""
Django settings for gambinos project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from django.conf import settings
import logging.config
import dj_database_url  # kept in case you want it later
import environ
from dotenv import load_dotenv

# =====================================================
# 🔧 CORE CONFIGURATION
# =====================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from project root
env_file = BASE_DIR / ".env"
if env_file.exists():
    load_dotenv(env_file)  # lets os.environ see values from .env

# Initialise django-environ
env = environ.Env(
    DEBUG=(bool, False),
)

# read .env again via environ (uses same .env)
if env_file.exists():
    environ.Env.read_env(env_file)

TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")
SITE_ID = 1
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"


# =====================================================
# 🔐 SECURITY / DEBUG
# =====================================================

# SECRET_KEY must be defined in .env
# e.g. SECRET_KEY=django-insecure-xxxxxxxxxxxxxxxxxxxx
SECRET_KEY = env("SECRET_KEY")

# DEBUG from .env (default False for safety)
DEBUG = env.bool("DEBUG", default=False)

# Allowed hosts – can override from .env if you want
ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=[".herokuapp.com", "127.0.0.1", "localhost"],
)

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "https://*.codeinstitute-ide.net",
        "https://*.herokuapp.com",
    ],
)


# =====================================================
# 📜 LOGGING
# =====================================================

# production-friendly logging config that outputs to both the console and a rotating log file
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} [{name}:{lineno}] {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/django.log"),
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "errors_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/errors.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "level": "ERROR",  # only log errors+
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file", "errors_file"],
        "level": "DEBUG",  # change to INFO / WARNING for prod
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file", "errors_file"],
            "level": "INFO",
            "propagate": False,
        },
        "reservation_book": {
            "handlers": ["console", "file", "errors_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}


# =====================================================
# 🔌 APPLICATION DEFINITION
# =====================================================

INSTALLED_APPS = [
    "django_admin_dracula",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_summernote",
    # "reservation_book",
    "phonenumber_field",
    "django_tables2",
    "django.contrib.sites",
    "reservation_book.apps.ReservationBookConfig",

    # Required by allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",  # optional but recommended

    "crispy_forms",
    "crispy_bootstrap5",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ROOT_URLCONF = "gambinos.urls"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "gambinos.wsgi.application"


# =====================================================
# 🗄 DATABASE – POSTGRES VIA DATABASE_URL WITH SQLITE FALLBACK
# =====================================================

# .env should contain:
# DATABASE_URL=postgresql://USER:PASSWORD@HOST:PORT/DBNAME?sslmode=require
#
# If DATABASE_URL is present -> Postgres (or whatever URL points to).
# If DATABASE_URL is missing -> falls back to local SQLite, and
# crucially no sslmode is passed to sqlite3 (so no TypeError).

DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}


# =====================================================
# 🔐 PASSWORD VALIDATION
# =====================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ==== dj-allauth authentication behaviour ====

# Keep usernames around and usable
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_USERNAME_REQUIRED = True

# Still collect emails and enforce them being unique
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True

# NEW style (for recent django-allauth)
ACCOUNT_LOGIN_METHODS = {"username", "email"}

# Backwards compatibility for older allauth, harmless if ignored
ACCOUNT_AUTHENTICATION_METHOD = "username_email"

# For development, don’t block logins just because emails aren’t verified
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True


# =====================================================
# 🌍 INTERNATIONALIZATION
# =====================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

PHONENUMBER_DB_FORMAT = "INTERNATIONAL"
PHONENUMBER_DEFAULT_REGION = "DE"


# =====================================================
# 📦 STATIC FILES
# =====================================================

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# =====================================================
# 🔑 PRIMARY KEY DEFAULT
# =====================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =====================================================
# 📧 EMAIL (READY FOR SMTP)
# =====================================================

# .env can define:
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_HOST_USER=your_gmail@gmail.com
# EMAIL_HOST_PASSWORD=your_app_password
# DEFAULT_FROM_EMAIL="Gambinos Restaurant & Lounge <your_gmail@gmail.com>"
# SERVER_EMAIL=your_gmail@gmail.com

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)

EMAIL_HOST = env("EMAIL_HOST", default="localhost")
EMAIL_PORT = env.int("EMAIL_PORT", default=25)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="Gambinos Restaurant & Lounge <no-reply@example.com>",
)

SERVER_EMAIL = env(
    "SERVER_EMAIL",
    default=EMAIL_HOST_USER or "no-reply@example.com",
)


# =====================================================
# 📨 FUTURE INTEGRATIONS (COMMENTED)
# =====================================================

# --- SendGrid Email Settings ---
# EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
# SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY")
# SENDGRID_SANDBOX_MODE_IN_DEBUG = False  # True = don’t really send emails
# SENDGRID_ECHO_TO_STDOUT = False         # Print emails to console in development
# DEFAULT_FROM_EMAIL = "oliver.p.hartmann@gmail.com"

# Twilio configuration
# TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID")
# TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN")
# TWILIO_PHONE_NUMBER = os.environ.get("TWILIO_PHONE_NUMBER")
