"""
Django settings for gambinos project.

Generated by 'django-admin startproject' using Django 4.2.x
"""

from pathlib import Path
import os
import sys
import environ


# =====================================================
# 🔧 CORE CONFIGURATION
# =====================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# django-environ
env = environ.Env(
    DEBUG=(bool, False),
)

# Load .env from project root (same folder as manage.py)
env_file = BASE_DIR / ".env"
if env_file.exists():
    environ.Env.read_env(env_file)

SITE_ID = 1


# =====================================================
# 🔐 SECURITY / DEBUG
# =====================================================
# IMPORTANT:
# - For local dev, keep a fallback so you can run without Heroku env.
SECRET_KEY = env("SECRET_KEY", default="dev-insecure-secret-key-change-me")

# ✅ Use django-environ consistently (avoids surprises)
DEBUG = env.bool("DEBUG", default=False)

# Hosts (CSV in .env supported: "127.0.0.1,localhost")
ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["127.0.0.1", "localhost"],
)

# CSRF trusted origins must include scheme (http/https)
# e.g. "http://127.0.0.1:8000,http://localhost:8000,https://yourdomain.com"
CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[],
)

# ✅ If DEBUG, force-add local origins so login POST doesn't 403
if DEBUG:
    local_origins = {
        "http://127.0.0.1:8000",
        "http://localhost:8000",
    }
    CSRF_TRUSTED_ORIGINS = list(set(CSRF_TRUSTED_ORIGINS) | local_origins)
else:
    # Production defaults if you don't provide env var
    if not CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS = [
            "https://*.herokuapp.com",
            "https://*.codeinstitute-ide.net",
        ]


# =====================================================
# 📜 LOGGING (keep it simple and safe)
# =====================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} [{name}:{lineno}] {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "reservation_book": {"handlers": ["console"], "level": "DEBUG", "propagate": False},
        "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}


# =====================================================
# 🔌 APPLICATION DEFINITION
# =====================================================
INSTALLED_APPS = [
    # Theme/admin add-ons
    "django_admin_dracula",

    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Summernote (keep, because your urls.py includes it)
    "django_summernote",

    # Your libs
    "phonenumber_field",
    "django_tables2",

    # Sites + allauth
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    # Crispy
    "crispy_forms",
    "crispy_bootstrap5",

    # Your app
    "reservation_book.apps.ReservationBookConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ROOT_URLCONF = "gambinos.urls"
WSGI_APPLICATION = "gambinos.wsgi.application"


# =====================================================
# 🎨 TEMPLATES
# =====================================================
TEMPLATES_DIR = BASE_DIR / "templates"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(TEMPLATES_DIR)],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]


# =====================================================
# 🗄 DATABASE
# =====================================================
RUNNING_TESTS = (
    "PYTEST_CURRENT_TEST" in os.environ
    or any("pytest" in arg or "py.test" in arg for arg in sys.argv)
)

if RUNNING_TESTS:
    DATABASES = {
        "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}
    }
else:
    # Use DATABASE_URL if present, else sqlite locally
    DATABASES = {
        "default": env.db(
            "DATABASE_URL",
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        )
    }

    # Connection reuse + safety knobs
    DATABASES["default"]["CONN_MAX_AGE"] = env.int("CONN_MAX_AGE", default=60)
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"].setdefault("connect_timeout", 5)

    # If Postgres, you may want atomic requests
    if DATABASES["default"]["ENGINE"] != "django.db.backends.sqlite3":
        DATABASES["default"]["ATOMIC_REQUESTS"] = True


# =====================================================
# 🔐 PASSWORD VALIDATION
# =====================================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# =====================================================
# ✅ ALLAUTH (your format)
# =====================================================
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]

ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
LOGIN_REDIRECT_URL = "my_reservations"
LOGOUT_REDIRECT_URL = "home"

ACCOUNT_ADAPTER = "reservation_book.adapters.CustomAccountAdapter"
ACCOUNT_FORMS = {"signup": "reservation_book.forms.CustomerSignupForm"}


# =====================================================
# 🌍 INTERNATIONALIZATION
# =====================================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Europe/Berlin"
USE_I18N = True
USE_TZ = True

PHONENUMBER_DB_FORMAT = "INTERNATIONAL"
PHONENUMBER_DEFAULT_REGION = "DE"


# =====================================================
# 🔒 SSL / COOKIE BEHAVIOR
# =====================================================
# Behind proxies (Heroku). Safe locally too.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Only force secure cookies in production.
if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# =====================================================
# 📦 STATIC + MEDIA FILE STORAGE
# =====================================================
STATIC_URL = "static/"
STATICFILES_DIRS = [str(BASE_DIR / "static")]
STATIC_ROOT = str(BASE_DIR / "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = str(BASE_DIR / "media")

# Django 4.2+ storage config:
# - "default" is REQUIRED for FileField uploads (summernote uses this)
# - "staticfiles" controls collectstatic/whitenoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# =====================================================
# 🔑 PRIMARY KEY DEFAULT
# =====================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =====================================================
# 📧 EMAIL (Brevo in prod, console locally unless overridden)
# =====================================================

def _clean_env_str(key: str, default: str = "") -> str:
    """
    Defensive: strips inline '# comments' and whitespace from .env values.
    This prevents weird unicode/comment artifacts from breaking SMTP auth.
    """
    raw = env(key, default=default)
    if raw is None:
        return ""
    raw = str(raw)
    if "#" in raw:
        raw = raw.split("#", 1)[0]
    return raw.strip()


# ✅ CHANGE: default is now False so local sends via Brevo unless you explicitly opt into console
USE_CONSOLE_EMAIL = env.bool("USE_CONSOLE_EMAIL", default=False)

if DEBUG and USE_CONSOLE_EMAIL:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = env(
        "EMAIL_BACKEND",
        default="django.core.mail.backends.smtp.EmailBackend",
    )

EMAIL_HOST = _clean_env_str("EMAIL_HOST", default="smtp-relay.brevo.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)

EMAIL_HOST_USER = _clean_env_str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = _clean_env_str("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = _clean_env_str(
    "DEFAULT_FROM_EMAIL",
    default="Gambinos Restaurant & Lounge <no-reply@gambinosrestaurantandlounge.com>",
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
